/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hadee
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jColorChooser3 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        S1Letter = new javax.swing.JTextField();
        Subject2 = new javax.swing.JTextField();
        Subject3 = new javax.swing.JTextField();
        Subject4 = new javax.swing.JTextField();
        Subject5 = new javax.swing.JTextField();
        S2Letter = new javax.swing.JTextField();
        Subject1 = new javax.swing.JTextField();
        S3Letter = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        AverageTF = new javax.swing.JTextField();
        S4Letter = new javax.swing.JTextField();
        S5Letter = new javax.swing.JTextField();
        GPATF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 102, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("My GPA ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Subjec1");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Subject2");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Subject3");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Subjec4");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Subject5");

        S1Letter.setEditable(false);
        S1Letter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S1LetterActionPerformed(evt);
            }
        });

        Subject2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject2ActionPerformed(evt);
            }
        });

        Subject4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject4ActionPerformed(evt);
            }
        });

        Subject5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject5ActionPerformed(evt);
            }
        });

        S2Letter.setEditable(false);
        S2Letter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S2LetterActionPerformed(evt);
            }
        });

        Subject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject1ActionPerformed(evt);
            }
        });

        S3Letter.setEditable(false);
        S3Letter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S3LetterActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        AverageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AverageTFActionPerformed(evt);
            }
        });

        S4Letter.setEditable(false);
        S4Letter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S4LetterActionPerformed(evt);
            }
        });

        S5Letter.setEditable(false);
        S5Letter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S5LetterActionPerformed(evt);
            }
        });

        GPATF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPATFActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Average");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("GPA");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Letter ");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Subject2)
                    .addComponent(Subject3)
                    .addComponent(Subject4)
                    .addComponent(Subject5)
                    .addComponent(Subject1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(S2Letter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S3Letter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S4Letter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S5Letter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(S1Letter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GPATF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addComponent(AverageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(143, 143, 143))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {S1Letter, S2Letter, S3Letter, S4Letter, S5Letter, Subject1, Subject2, Subject3, Subject4, Subject5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Subject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S1Letter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Subject2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(S2Letter, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Subject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(S3Letter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subject4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(S4Letter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subject5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(S5Letter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPATF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AverageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(67, 67, 67))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {S1Letter, S2Letter, S3Letter, S4Letter, S5Letter, Subject1, Subject2, Subject3, Subject4, Subject5});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void S1LetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S1LetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S1LetterActionPerformed

    private void S2LetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S2LetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S2LetterActionPerformed

    private void Subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject1ActionPerformed

    private void Subject5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject5ActionPerformed

    private void S3LetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S3LetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S3LetterActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void AverageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AverageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AverageTFActionPerformed

    private void S4LetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S4LetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S4LetterActionPerformed

    private void S5LetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S5LetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S5LetterActionPerformed

    private void GPATFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPATFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPATFActionPerformed

    private void Subject2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject2ActionPerformed

    private void Subject4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Subject1Score, Subject2Score, Subject3Score, Subject4Score, Subject5Score;
        double Average;
        double GPA=0;
        
        
        Subject1Score=Subject1.getText();
        Subject2Score=Subject2.getText();
        Subject3Score=Subject3.getText();
        Subject4Score=Subject4.getText();
        Subject5Score=Subject5.getText();
      
        double Subject1= Double.parseDouble(Subject1Score);
        double Subject2= Double.parseDouble(Subject2Score);
        double Subject3= Double.parseDouble(Subject3Score);
        double Subject4= Double.parseDouble(Subject4Score);
        double Subject5= Double.parseDouble(Subject5Score);
        
             


        if(Subject1 >= 95) {
            S1Letter.setText("A+");
           
            GPA =GPA + 5.0;
        } else if(Subject1 >= 90 && Subject1 < 95){
            S1Letter.setText("A");
         GPA =GPA + 4.5;}
        else if(Subject1 >= 85 && Subject1 < 90){
            S1Letter.setText("B+");
         GPA =GPA + 4.0;}
        else if(Subject1 >= 80 && Subject1 < 85){
            S1Letter.setText("B");
         GPA =GPA + 3.5;}
        else if(Subject1 >= 75 && Subject1 < 80){
            S1Letter.setText("C+");
         GPA =GPA + 3.0;}
        else if(Subject1 >= 70 && Subject1 < 75){
            S1Letter.setText("C");
         GPA =GPA + 2.5;}
        else if(Subject1 >= 65 && Subject1 < 70){
            S1Letter.setText("D+");
         GPA =GPA + 2.0;}
        else if(Subject1 >= 60 && Subject1 < 65){
            S1Letter.setText("D");
         GPA =GPA + 1.5;}
        else if(Subject1 < 60){
            S1Letter.setText("F");
         GPA =GPA + 1.0;
    
    }//GEN-LAST:event_jButton1ActionPerformed
         if(Subject2 >= 95) {
            S2Letter.setText("A+");
           
            GPA =GPA + 5.0;
        } else if(Subject2 >= 90 && Subject2 < 95){
            S2Letter.setText("A");
         GPA =GPA + 4.5;}
        else if(Subject2 >= 85 && Subject2 < 90){
            S2Letter.setText("B+");
         GPA =GPA + 4.0;}
        else if(Subject2 >= 80 && Subject2 < 85){
            S2Letter.setText("B");
         GPA =GPA + 3.5;}
        else if(Subject2 >= 75 && Subject2 < 80){
            S2Letter.setText("C+");
         GPA =GPA + 3.0;}
        else if(Subject2 >= 70 && Subject2 < 75){
            S2Letter.setText("C");
         GPA =GPA + 2.5;}
        else if(Subject2 >= 65 && Subject2 < 70){
            S2Letter.setText("D+");
         GPA =GPA + 2.0;}
        else if(Subject2>= 60 && Subject2< 65){
            S2Letter.setText("D");
         GPA =GPA + 1.5;}
        else if(Subject2 < 60){
            S2Letter.setText("F");
         GPA =GPA + 1.0;
    
    }
              if(Subject3 >= 95) {
            S3Letter.setText("A+");
           
            GPA =GPA + 5.0;
        } else if(Subject3 >= 90 && Subject3 < 95){
            S3Letter.setText("A");
         GPA =GPA + 4.5;}
        else if(Subject3 >= 85 && Subject3< 90){
            S3Letter.setText("B+");
         GPA =GPA + 4.0;}
        else if(Subject3 >= 80 && Subject3 < 85){
            S3Letter.setText("B");
         GPA =GPA + 3.5;}
        else if(Subject3>= 75 && Subject3 < 80){
            S3Letter.setText("C+");
         GPA =GPA + 3.0;}
        else if(Subject3 >= 70 && Subject3 < 75){
            S3Letter.setText("C");
         GPA =GPA + 2.5;}
        else if(Subject3 >= 65 && Subject3< 70){
            S3Letter.setText("D+");
         GPA =GPA + 2.0;}
        else if(Subject3 >= 60 && Subject3 < 65){
            S3Letter.setText("D");
         GPA =GPA + 1.5;}
        else if(Subject3 < 60){
            S3Letter.setText("F");
         GPA =GPA + 1.0;
    
    }
                   if(Subject4 >= 95) {
            S4Letter.setText("A+");
           
            GPA =GPA + 5.0;
        } else if(Subject4 >= 90 && Subject4 < 95){
            S1Letter.setText("A");
         GPA =GPA + 4.5;}
        else if(Subject4>= 85 && Subject4 < 90){
            S4Letter.setText("B+");
         GPA =GPA + 4.0;}
        else if(Subject4>= 80 && Subject4< 85){
            S4Letter.setText("B");
         GPA =GPA + 3.5;}
        else if(Subject4 >= 75 && Subject4< 80){
            S4Letter.setText("C+");
         GPA =GPA + 3.0;}
        else if(Subject4 >= 70 && Subject4< 75){
            S4Letter.setText("C");
         GPA =GPA + 2.5;}
        else if(Subject4 >= 65 && Subject4< 70){
            S4Letter.setText("D+");
         GPA =GPA + 2.0;}
        else if(Subject4 >= 60 && Subject4 < 65){
            S4Letter.setText("D");
         GPA =GPA + 1.5;}
        else if(Subject4 < 60){
            S4Letter.setText("F");
         GPA =GPA + 1.0;
    
    }
                        if(Subject5 >= 95) {
            S5Letter.setText("A+");
           
            GPA =GPA + 5.0;
        } else if(Subject5 >= 90 && Subject5 < 95){
            S5Letter.setText("A");
         GPA =GPA + 4.5;}
        else if(Subject5 >= 85 && Subject5 < 90){
            S5Letter.setText("B+");
         GPA =GPA + 4.0;}
        else if(Subject5 >= 80 && Subject5< 85){
            S5Letter.setText("B");
         GPA =GPA + 3.5;}
        else if(Subject5 >= 75 && Subject5< 80){
            S5Letter.setText("C+");
         GPA =GPA + 3.0;}
        else if(Subject5 >= 70 && Subject5 < 75){
            S5Letter.setText("C");
         GPA =GPA + 2.5;}
        else if(Subject5 >= 65 && Subject5< 70){
            S5Letter.setText("D+");
         GPA =GPA + 2.0;}
        else if(Subject5 >= 60 && Subject5< 65){
            S5Letter.setText("D");
         GPA =GPA + 1.5;}
        else if(Subject5 < 60){
            S5Letter.setText("F");
         GPA =GPA + 1.0;
    
    }
                  


Average=((Subject1+Subject2+Subject3+Subject4+Subject5) / 5);
   GPA=GPA/5;
   GPATF.setText(Double.toString(GPA));
   AverageTF.setText(Double.toString(Average));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AverageTF;
    private javax.swing.JTextField GPATF;
    private javax.swing.JTextField S1Letter;
    private javax.swing.JTextField S2Letter;
    private javax.swing.JTextField S3Letter;
    private javax.swing.JTextField S4Letter;
    private javax.swing.JTextField S5Letter;
    private javax.swing.JTextField Subject1;
    private javax.swing.JTextField Subject2;
    private javax.swing.JTextField Subject3;
    private javax.swing.JTextField Subject4;
    private javax.swing.JTextField Subject5;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
